name: 'stably-runner'
description: 'Use this Github action to run tests on https://stably.ai/'
author: 'Stably'

# Define your inputs here.
inputs:
  project_id:
    description: 'Your project id'
    required: true
  api_key:
    description: 'Your api key'
    required: true

# Define your outputs here.
outputs:
  success:
    description: 'Bool if run was successful'

runs:
  using: node20
  main: dist/index.js
